### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [Akylas/alpimaps#15]
Well, guess you're waiting for this one already with the new release still hot, so I can't disappoint you, right?

```
! repo/akylas.alpi.maps_251.apk declares sensitive permission(s):
 android.permission.ACCESS_COARSE_LOCATION android.permission.ACCESS_FINE_LOCATION
 android.permission.MANAGE_EXTERNAL_STORAGE android.permission.READ_EXTERNAL_STORAGE
 android.permission.CAMERA android.permission.READ_PHONE_STATE
```

got most of them covered already (I hope):

```yaml
      android.permission.ACCESS_COARSE_LOCATION: needed for navigation
      android.permission.ACCESS_FINE_LOCATION: needed for navigation
      android.permission.MANAGE_EXTERNAL_STORAGE: needed to access data generated off-device e.g. using the alpimaps_data_generator
      android.permission.READ_EXTERNAL_STORAGE: needed to access data generated off-device e.g. using the alpimaps_data_generator
```

which leaves `CAMERA` and `READ_PHONE_STATE`. I've searched the code, but not being an Android dev (and especially having no ideas about Svelte and TypeScript), I had no success there. Can you once more help me out, please?

![image](https://github.com/Akylas/alpimaps/assets/6781438/3b9a10a0-8e0b-4141-ae71-9b63fd268941)

And in case I didn't yet mention that `DEPENDENCY_INFO_BLOCK`, which is only useful to Google but to nobody else:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.
